// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705123025_AddAlbumsAndMemes")]
    partial class AddAlbumsAndMemes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_content");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Meme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("album_id");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MemeTemplate")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("meme_template");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("memes", (string)null);
                });

            modelBuilder.Entity("Backend.Models.MemeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("example");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("meme_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A baby holding sand in his fist looking determined, representing unexpected success or minor victories.",
                            Example = "Me finding a 10-dollar bill in my old winter coat.",
                            Name = "successKid",
                            Url = "https://res.cloudinary.com/dplzxrvqy/image/upload/v1734749139/meme_templates/wgrmqej6jktwoh8qwdt8.webp"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A skeleton sitting on a bench, representing a long or endless wait for something.",
                            Example = "Me waiting for my food delivery that I ordered 1 minute ago.",
                            Name = "waitingSkeleton",
                            Url = "https://res.cloudinary.com/dplzxrvqy/image/upload/v1734749140/meme_templates/bsorrrb59szpbxvlqfzh.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Description = "An elderly woman looking closely at a laptop screen with a happy, naive expression.",
                            Example = "Me looking for the download button on a shady torrent site.",
                            Name = "grandmaFindsTheInternet",
                            Url = "https://res.cloudinary.com/dplzxrvqy/image/upload/v1734749140/meme_templates/ohjrh7u1s5yo2k8wg2qf.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A young girl smiling deviously at the camera while a house burns in the background.",
                            Example = "When you carry the team but your team acts like they contributed as much.",
                            Name = "disasterGirl",
                            Url = "https://res.cloudinary.com/dplzxrvqy/image/upload/v1734749140/meme_templates/b2eenvdnj2bwjobya5b9.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Two muscular arms shaking hands, representing agreement or common ground between two different parties.",
                            Example = "C++ developers and rust developers both hating JavaScript.",
                            Name = "epicHandshake",
                            Url = "https://res.cloudinary.com/dplzxrvqy/image/upload/v1734749140/meme_templates/dnhvaz7ifh2qbpzrvgue.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Leonardo DiCaprio laughing while holding a cocktail in Django Unchained, conveying mocking amusement or sarcasm.",
                            Example = "When your friend finally pays you back.",
                            Name = "laughingLeo",
                            Url = "https://res.cloudinary.com/dplzxrvqy/image/upload/v1734749141/meme_templates/qrwnaqiosoly5o4cwmjx.png"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A puppet monkey looking forward then turning its eyes away, representing avoiding eye contact or ignoring an obvious truth.",
                            Example = "Me ignoring my compile errors and hoping they go away on the next run.",
                            Name = "monkeyLookingAway",
                            Url = "https://res.cloudinary.com/dplzxrvqy/image/upload/v1734749140/meme_templates/mfmddhpqbba09ks3ytyi.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Leonardo DiCaprio smiling and raising a glass in The Great Gatsby, expressing approval, congratulations, or cheers.",
                            Example = "To the one guy on StackOverflow who answered my exact problem in 2012.",
                            Name = "leonardoDiCaprioCheers",
                            Url = "https://res.cloudinary.com/dplzxrvqy/image/upload/v1734749140/meme_templates/esnqhfjcm5w8bnzp7g7z.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A woman whispering into another woman's ear, causing an extreme reaction of goosebumps, expressing a highly exciting statement.",
                            Example = "Developer: \"We are finally deleting the legacy codebase tomorrow.\"",
                            Name = "whisperAndGoosebumps",
                            Url = "https://res.cloudinary.com/dplzxrvqy/image/upload/v1734749140/meme_templates/yigvofyucfigmwc0jee7.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Description = "A cartoon dog character wearing a sweater standing casually, representing a relaxed state of mind under pressure.",
                            Example = "Backend server crashing while I stay completely chill.",
                            Name = "chillGuy",
                            Url = "https://res.cloudinary.com/dplzxrvqy/image/upload/v1734749140/meme_templates/ovushouholjp0u08l9qr.jpg"
                        },
                        new
                        {
                            Id = 11,
                            Description = "A man pointing to his head, indicating intelligence, smart decisions, or witty workarounds.",
                            Example = "You can't have bugs in your code if you don't write any code.",
                            Name = "thinkingBlackGuy",
                            Url = "https://res.cloudinary.com/dplzxrvqy/image/upload/v1734749140/meme_templates/eus5k9oectd3lbgozgx9.jpg"
                        });
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jwt_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("picture_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Album", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Albums")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Meme", b =>
                {
                    b.HasOne("Backend.Models.Album", "Album")
                        .WithMany("Memes")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Album", b =>
                {
                    b.Navigation("Memes");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
